"""add phone and updated_at to users

Revision ID: 96b8bd4c11ec
Revises: 7f107f3de01d
Create Date: 2026-05-16 10:47:41.461192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96b8bd4c11ec'
down_revision = '7f107f3de01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inwards',
    sa.Column('inward_id', sa.Integer(), nullable=False),
    sa.Column('inward_number', sa.String(length=30), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('inwarded_by', sa.Integer(), nullable=False),
    sa.Column('inwarded_at', sa.DateTime(), nullable=True),
    sa.Column('total_items_expected', sa.Integer(), nullable=True),
    sa.Column('total_items_received', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inwarded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_tasks.pickup_id'], ),
    sa.PrimaryKeyConstraint('inward_id'),
    sa.UniqueConstraint('inward_number')
    )
    op.create_table('pickup_items',
    sa.Column('pickup_item_id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.item_id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickup_tasks.pickup_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['reusable_item_tags.tag_id'], ),
    sa.PrimaryKeyConstraint('pickup_item_id')
    )
    op.create_table('inward_items',
    sa.Column('inward_item_id', sa.Integer(), nullable=False),
    sa.Column('inward_id', sa.Integer(), nullable=False),
    sa.Column('pickup_item_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('is_received', sa.Boolean(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['inward_id'], ['inwards.inward_id'], ),
    sa.ForeignKeyConstraint(['pickup_item_id'], ['pickup_items.pickup_item_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['reusable_item_tags.tag_id'], ),
    sa.PrimaryKeyConstraint('inward_item_id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_category', sa.String(length=100), nullable=False))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('service_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'item_types', ['item_type_id'], ['item_type_id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_pickup_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('CREATED', 'IN_PROCESS', 'READY_FOR_DELIVERY', 'DELIVERED', 'BILLABLE', 'INVOICED', name='orderstatus'),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.create_unique_constraint(None, ['order_number'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('pickup_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_number', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('bag_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('CREATED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='pickupstatus'),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['pickup_number'])
        batch_op.create_foreign_key(None, 'users', ['pickup_agent_id'], ['id'])
        batch_op.drop_column('picked_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('phone')

    with op.batch_alter_table('pickup_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('CREATED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='pickupstatus'),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('bag_count')
        batch_op.drop_column('pickup_number')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('CREATED', 'IN_PROCESS', 'READY_FOR_DELIVERY', 'DELIVERED', 'BILLABLE', 'INVOICED', name='orderstatus'),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('scheduled_pickup_date')
        batch_op.drop_column('created_by')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('item_category')

    op.drop_table('inward_items')
    op.drop_table('pickup_items')
    op.drop_table('inwards')
    # ### end Alembic commands ###
