"""Initial migration

Revision ID: eb9b076b9ad3
Revises: 
Create Date: 2026-01-05 00:00:04.275200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9b076b9ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bags',
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'DAMAGED', name='bagstatus'), nullable=True),
    sa.PrimaryKeyConstraint('bag_id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('item_types',
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('item_type_id')
    )
    op.create_table('states_ut',
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('is_union_territory', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('state_code')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.Enum('B2C', 'B2B', name='customertype'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('billing_cycle', sa.String(length=30), nullable=True),
    sa.Column('tagging_enabled', sa.Boolean(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['state_code'], ['states_ut.state_code'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('pricing_rules',
    sa.Column('pricing_id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_types.item_type_id'], ),
    sa.PrimaryKeyConstraint('pricing_id')
    )
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_type', sa.Enum('MONTHLY', 'ON_DEMAND', name='invoicetype'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('reusable_item_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('tag_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'LOST', 'DAMAGED', name='tagstatus'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_code')
    )
    op.create_table('credit_notes',
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('credit_note_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROCESS', 'READY_FOR_DELIVERY', 'DELIVERED', 'BILLABLE', 'INVOICED', name='orderstatus'), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', name='paymentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('bag_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.bag_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('delivery_tasks',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('delivery_agent_id', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'IN_PROGRESS', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('order_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['reusable_item_tags.tag_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('pickup_tasks',
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('pickup_agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='pickupstatus'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('pickup_id')
    )
    op.create_table('refunds',
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refund_status', sa.Enum('INITIATED', 'COMPLETED', 'FAILED', name='refundstatus'), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.credit_note_id'], ),
    sa.PrimaryKeyConstraint('refund_id')
    )
    op.create_table('delivery_bags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('bag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_tasks.delivery_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', 'bag_id', name='uq_delivery_bag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_bags')
    op.drop_table('refunds')
    op.drop_table('pickup_tasks')
    op.drop_table('order_items')
    op.drop_table('delivery_tasks')
    op.drop_table('bag_assignments')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('credit_notes')
    op.drop_table('reusable_item_tags')
    op.drop_table('invoices')
    op.drop_table('pricing_rules')
    op.drop_table('customers')
    op.drop_table('states_ut')
    op.drop_table('item_types')
    op.drop_table('bags')
    # ### end Alembic commands ###
